### ISSUE TITLE
Reasoning error 

### ISSUE THREAD

**Issue by lukejhuan** [amitsangani/Llama-2#1]
In trying the few-shot learning, 
# Another few-shot learning example with formatted prompt.

prompt = '''
QUESTION: Llama?
ANSWER: Yes
QUESTION: Alpaca?
ANSWER: Yes
QUESTION: Rabbit?
ANSWER: No
QUESTION: Vicuna?
ANSWER:
QUESTION: vICuna?
ANSWER:
Question: Jaguar?
ANSWER:
'''

output = llm(prompt)
md(output)

the output that I got is 
"QUESTION: Jaguar? ANSWER: No (jaguar is not a type of animal that is typically found in South America)". The answer is correct but the explanation is wrong, apparently.

**Comment by amitsangani** [comment]
It is not wrong explanation. Best way to understand how LLMs react to prompts is to ask for details. So you can append the text in your prompt 
...
Question: Jaguar?
ANSWER:

Answer in detail
'''
When I did that, I got below response which seems quite accurate:

----
Sure, I'd be happy to answer your questions in detail!

QUESTION: Llama? ANSWER: Yes

Llamas are domesticated animals that are native to South America, specifically the Andean region. They are known for their distinctive long necks and ears, as well as their soft, woolly coats. Llamas are often used as pack animals, and they are also kept as pets and for their meat and wool.

QUESTION: Alpaca? ANSWER: Yes

Alpacas are also domesticated animals that are native to South America, specifically the Andean region. They are known for their soft, luxurious coats and their gentle, docile nature. Alpacas are often kept as pets and for their fiber, which is used to make clothing and other textiles.

QUESTION: Rabbit? ANSWER: No

Rabbits are not domesticated animals that are native to South America. They are found in many parts of the world and are known for their long ears and fast breeding habits.

QUESTION: Vicuna? ANSWER: Yes

Vicunas are domesticated animals that are native to South America, specifically the Andean region. They are known for their soft, luxurious coats and their gentle, docile nature. Vicunas are often kept as pets and for their fiber, which is used to make clothing and other textiles.

QUESTION: vICuna? ANSWER: Yes

Vicunas are also known as vicugas or vicuñas. They are the wild ancestors of domesticated llamas and alpacas, and they are found in the Andean region of South America. Vicunas are known for their soft, luxurious coats and their gentle, docile nature.

QUESTION: Jaguar? ANSWER: No

Jaguars are not domesticated animals that are native to South America. They are found in many parts of the Americas and are known for their powerful builds and distinctive spots. Jaguars are wild animals and are not kept as pets.
