### ISSUE TITLE
ModuleNotFoundError: No module named 'unstructured_pytesseract'

### ISSUE THREAD

**Issue by kandeldeepak46** [amitsangani/Llama-2#2]
![image](https://github.com/amitsangani/Llama-2/assets/33603333/fe0421ec-6530-418e-9b97-48993e02064c)

**Comment by amitsangani** [comment]
Are you running this on jupyter instead of Google Colab? If so, you might want to try "!pip install pytesseract" and then see if it resolves.

**Comment by kandeldeepak46** [comment]
I am running on Google Colab and installed all the dependencies accordingly 
```python
!pip install pikepdf
!pip install pypdf
!pip install unstructured
!pip install pytesseract
!pip install PyPDF2
```

But it is still showing the error

**Comment by kandeldeepak46** [comment]
```
%pip install -qU \
    replicate \
    langchain \
    sentence_transformers \
    pdf2image \
    pdfminer \
    pdfminer.six \
    unstructured_pytesseract \
    unstructured_inference \
    faiss-gpu
```
I had to update the code in the first notebook...it works now :)
